apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.shujaakbar.com
spec:
  group: shujaakbar.com
  scope: Namespaced
  names:
    plural: dummysites
    singular: dummysite
    kind: DummySite
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                website_url:
                  type: string
              required:
                - website_url
