FROM python:3.11-slim

WORKDIR /app

# Copy requirements (even if empty)
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy app
COPY rand_generator.py ./

ENV PYTHONUNBUFFERED=1

CMD ["python3", "rand_generator.py"]
