apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-output-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shujaakbar2020/KubernetesSubmissions
    path: log_output/overlays/staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
